"""initial_tables

Revision ID: eabad67c2013
Revises: 
Create Date: 2026-03-10 06:24:40.268014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eabad67c2013'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=512), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('primary_language', sa.String(length=100), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('forks', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_commit_sha', sa.String(length=40), nullable=True),
    sa.Column('processing_status', sa.String(length=20), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_commits', sa.Integer(), nullable=False),
    sa.Column('total_contributors', sa.Integer(), nullable=False),
    sa.Column('created_in_db', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_in_db', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name')
    )
    op.create_table('commits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('commit_hash', sa.String(length=40), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('author_email', sa.String(length=255), nullable=True),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('files_changed', sa.Integer(), nullable=False),
    sa.Column('additions', sa.Integer(), nullable=False),
    sa.Column('deletions', sa.Integer(), nullable=False),
    sa.Column('parent_hash', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_commits_repo_date', 'commits', ['repo_id', 'committed_at'], unique=False)
    op.create_table('contributors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('total_commits', sa.Integer(), nullable=False),
    sa.Column('total_additions', sa.Integer(), nullable=False),
    sa.Column('total_deletions', sa.Integer(), nullable=False),
    sa.Column('first_commit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_commit_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'email', name='uq_contributor_repo_email')
    )
    op.create_table('file_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('commit_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('change_type', sa.String(length=20), nullable=True),
    sa.Column('additions', sa.Integer(), nullable=False),
    sa.Column('deletions', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commit_id'], ['commits.id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_file_changes_path', 'file_changes', ['repo_id', 'file_path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_file_changes_path', table_name='file_changes')
    op.drop_table('file_changes')
    op.drop_table('contributors')
    op.drop_index('idx_commits_repo_date', table_name='commits')
    op.drop_table('commits')
    op.drop_table('repositories')
    # ### end Alembic commands ###
